"""rename case id

Revision ID: ad73f4be7a29
Revises: 017dc17819fd
Create Date: 2025-01-05 19:48:40.774200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad73f4be7a29'
down_revision: Union[str, None] = '017dc17819fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_records', sa.Column('case_id', sa.String(), nullable=False))
    op.drop_column('case_records', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_records', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('case_records', 'case_id')
    # ### end Alembic commands ###
